Chip mbed ip integration
ARMmbed/connectedhomeip pull request #140
Opened 2021-04-26 06:32 UTC by ATmobica

#### Problem
Merge chip-mbed-ip intergration branch

 #### Summary of Changes
Mbed BSD socket implementation
Cypress board support
Lock-app application

2021-04-26 14:25 UTC, pan- requested changes
I left few points if improvement that we can fix now. @ATmobica Can you take care of these then I will merge if there is no objections from you @lukgni @tymoteuszblochmobica

2021-04-26 14:25 UTC, pan- commented on src/platform/mbed/net/src/net_dns.cpp
> +                // to  do free res  to avoid memory leak
Can it be implemented ?

2021-04-26 14:25 UTC, pan- commented on src/platform/mbed/net/src/net_dns.cpp
> +        free(ai);
`delete` must be used as the `addrinfo` is allocated with `new` and not `malloc`.
`ai->ai_addr` must be deleted too.

2021-04-26 17:23 UTC, ATmobica commented on config/mbed/CMakeLists.txt
> +list(APPEND CHIP_CFLAGS
CHIP_CFLAGS is for GN propagation, CHIP_DEFINES is for cmake building - add to the main target.

2021-04-26 17:28 UTC, ATmobica commented on src/inet/UDPEndPoint.cpp
> +        lSystemLayer.WakeSelect();
This change is for UDP client implementation. I mentioned it once. We didn't call listen() function for the client. But when we send something we need to trigger select() and set a listening state to be ready to receive data from the server.

2021-04-27 07:12 UTC, pan- commented on src/inet/UDPEndPoint.cpp
> +        lSystemLayer.WakeSelect();
Thanks for the remainder.

2021-04-27 08:58 UTC, pan- approved these changes
LGTM

2021-04-27 08:58 UTC, merged