Test CI integration
ARMmbed/connectedhomeip pull request #185
Opened 2021-07-09 13:41 UTC by ATmobica

#### Problem
Add unit and integration testing to CI based on GitHub workflow and LAVA tool

 #### Summary of Changes
 Add LAVA support to the CHIP project
Create workflows to run unit and integration tests
Add workflow to build chip tools

Implement scripts to Mbed application testing:
- setup environments for testing
- run unit and integration tests
- lava job templates for running testing

Improve and fix integration tests cases

2021-07-12 10:52 UTC, lukgni requested changes

2021-07-12 10:52 UTC, lukgni commented on scripts/tests/mbed/lava_integration_tests.yml
> +      name: lgniadzik/chip-mbed-lava-device:latest
DITTO

2021-07-12 10:52 UTC, lukgni commented on scripts/tests/mbed/lava_unit_tests.yml
> +      name: lgniadzik/chip-mbed-lava-device:latest
DITTO

2021-07-12 10:52 UTC, lukgni commented on .github/workflows/run-integration-test-mbed.yaml
> +        run: exit 1
DITTO

2021-07-12 10:52 UTC, lukgni commented on .github/workflows/mbed_ci_stress_test.yaml
> +            - run: echo "Trigger Mbed CI actions"
No new line at the end of the file - it's good to add it now instead of being block by upstream's restyler.

2021-07-12 10:52 UTC, lukgni commented on .github/workflows/run-unit-test-mbed.yaml
> +        run: exit 1
DITTO

2021-07-12 10:52 UTC, lukgni commented on src/test_driver/mbed/integration_tests/shell/test_server.py
> +    assert ret != None and len(ret) > 1
DITTO

2021-07-12 10:52 UTC, lukgni commented on src/test_driver/mbed/integration_tests/test_set.in
> +lock-app
DITTO

2021-07-12 10:52 UTC, lukgni commented on src/test_driver/mbed/unit_tests/pytest/test_unittests.py
> +    assert int(result[0]) < 15
DITTO

2021-07-12 10:52 UTC, lukgni commented on .github/workflows/unit-test-mbed.yaml
> +# Copyright (c) 2020 Project CHIP Authors
2020 -> 2021

2021-07-12 10:52 UTC, lukgni commented on scripts/tests/mbed/lava_integration_tests.yml
> +          - /bin/bash CHIP/scripts/tests/mbed/integration_test_env.sh stop || lava-test-raise "Close env FAILED"
DITTO

2021-07-12 10:52 UTC, lukgni commented on scripts/tests/mbed/lava_unit_tests.yml
> +          - echo "Unit tests completed"
DITTO

2021-07-12 10:52 UTC, lukgni commented on src/test_driver/mbed/unit_tests/pytest/pytest.ini
> +log_cli_format = %(asctime)s.%(msecs)03d   %(levelname)s   %(message)s
DITTO

2021-07-13 22:43 UTC, lukgni commented on .github/workflows/run-integration-test-mbed.yaml
> +            exit 1
To get this work we have to use bash as a default shell for all jobs in this workflow.
I've already fixed this in #188

2021-07-14 09:07 UTC, ATmobica commented on .github/workflows/build_cr.yaml
> +    - cron:  '0 11 * * *'
Fixed in #188

2021-07-14 09:07 UTC, ATmobica commented on scripts/tests/mbed/lava_integration_tests.yml
> +      name: lgniadzik/chip-mbed-lava-device:latest
Fixed in #188

2021-07-14 09:08 UTC, ATmobica commented on .github/workflows/run-integration-test-mbed.yaml
> +        run: exit 1
Fixed in #188

2021-07-14 09:08 UTC, ATmobica commented on .github/workflows/build_cr.yaml
> +            DOCKER_CR_IMAGE: lgniadzik/chip-build:latest
Fixed in #188

2021-07-14 09:08 UTC, ATmobica commented on scripts/tests/mbed/lava_unit_tests.yml
> +      name: lgniadzik/chip-mbed-lava-device:latest
Fixed in #188

2021-07-14 10:50 UTC, lukgni approved these changes

2021-07-14 22:23 UTC, lukgni commented
After moving to GitHub Container registry (and fixing issue with uppercase letters in repository owner name) it looks like everything works as expected (as before):
- container registry with images: [LINK](https://github.com/orgs/ARMmbed/packages)
- cross-compiled chip-tool/device controller: [LINK](https://github.com/ARMmbed/connectedhomeip/actions/runs/1031772652)
- running unit tests: [LINK](https://github.com/ARMmbed/connectedhomeip/actions/runs/1031034439)
- running functional test: [LINK](https://github.com/ARMmbed/connectedhomeip/actions/runs/1031898971)

2021-07-14 22:57 UTC, pan- commented
The last link show failures in the package (Bluetooth not initialized ?). 
Lets merge this and work on stability. 

> 2021-07-14T22:25:06 Exception ignored in: <function BluezManager.__del__ at 0xffff8915e040>
2021-07-14T22:25:06 Traceback (most recent call last):
2021-07-14T22:25:06   File \"/usr/local/lib/python3.8/dist-packages/chip/ChipBluezMgr.py\", line 821, in __del__
2021-07-14T22:25:06 AttributeError: 'BluezManager' object has no attribute 'disconnect'
2021-07-14T22:25:06 Fatal Python error: Segmentation fault
2021-07-14T22:25:06 
2021-07-14T22:25:06 Thread 0x0000ffff8b1a9010 (most recent call first):
2021-07-14T22:25:06 <no Python frame>
2021-07-14T22:25:07 CHIP/scripts/tests/mbed/run_integration_tests.sh: line 40:  4419 Segmentation fault      (core dumped) pytest -rAV --platforms=\"$platform_name\" --network=$AP_SSID:$AP_PASSWORD --echo_server=$AP_GATEWAY:$ECHO_SERVER_PORT --chip_tools_dir=$CHIP_TOOLS_DIR $CHIP_DIR/src/test_driver/mbed/integration_tests/\"$test\"
2021-07-14T22:25:07 Integration test for shell application image on CY8CPROTO_062_4343W device failed

2021-07-14 22:57 UTC, pan- approved these changes

2021-07-14 22:59 UTC, merged