Add vscode tasks for flashing and debugging Mbed Shell examples
ARMmbed/connectedhomeip pull request #86
Opened 2021-02-26 03:10 UTC by lukgni

#### Problem

Missing capability to flash and debug mbed shell examples in vscode.

As someone may notice, I didn't change profile of build  shell application to 'debug' - ConnectivyManagerImpl.h stub causes a problem when we want to build application with debug profile (undefined reference in multiple places). 
I decided to not fix this issue within this change because problem probably will be solved when we merge wifi or ble work into 'development' branch (as they extend ConnectivityManagerImpl.h) 

 #### Summary of Changes
Update .devcontainer.json to pass through usb debug probe from host to vscode container.
Add flash tasks to tasks.json, add sepearted tast for building shell example on DISCO board and rename build tasks.
Add debug launch configuration for debugging mbed shell example.
Add pyocd, pyusb modules to the final vscode container.
Add mbed_example_utils.sh helper script for simplify calling pyocd within vscode tasks.

 Fixes #74
 Fixes #75 

 To verify this PR for DISCO board, Please apply #85 first.

2021-03-01 11:28 UTC, pan- commented
@fkjagodzinski Can you try this PR on linux ?

2021-03-01 12:57 UTC, pan- requested changes
I tested this PR locally and encountered few issues: 
- `mbed-tools` has been updated. Version 7 supports multiple builds (target, toolchain, profile) but it requires some adjustment to our CMakeLists.txt file:
`set(MBED_CONFIG_PATH ${CMAKE_CURRENT_SOURCE_DIR}/.mbedbuild CACHE INTERNAL "")` => set(MBED_CONFIG_PATH ${CMAKE_CURRENT_BINARY_DIR} CACHE INTERNAL ""). 
It also means we don't have to fiddle with paths in `mbed_example.sh`. I propose we fix mbed-tools to version 6 and update it to version 7 next sprint. 
- `libncurse` is missing and gdb doesn't start. It must be installed by the container.

2021-03-01 14:31 UTC, pan- commented
There is still some build issues, I supposed it is due to `mbed-tools` being used which is v7.

2021-03-02 01:23 UTC, lukgni commented
@pan- #88 solves issue with mbed-tools v7. 
Additionally it improves a little bit creating build output directory structure so we could reuse it as feature for debug/flash tasks
(as a possibility to have debug/release/develop builds in separated directory).

2021-03-02 01:44 UTC, lukgni commented on .vscode/tasks.json
> +            "label": "Build Mbed Shell example (NRF52840-DK)",
Done.

2021-03-02 12:19 UTC, pan- approved these changes
Thanks @lukgni ~~Can you rebase your branch against development ?~~ I merged #88 .

2021-03-02 12:39 UTC, ATmobica approved these changes

2021-03-02 13:33 UTC, merged